# ~/.config/starship.toml

add_newline = true

# ------------------------------------------
# Starship Config
# ------------------------------------------

format = """
[](#DBD7BA)\
[󱗞 ](bg:#DBD7BA fg:#090c0c)\
[](bg:#627d9a fg:#DBD7BA)\
$directory\
[](#627d9a)\
[ ](#364A82)\
[](fg:#364A82)\
[](bg:#364A82 fg:#7E9CD8)\
$git_branch\
$git_status\
[](fg:#364A82)\
[ ](#364A82)\
$nodejs\
$rust\
$golang\
$php\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#627d9a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
style = "bg:#364A82"
format = '[ [$branch](fg:#769ff0 bg:#364A82)]($style)'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

style = "bg:#364A82"
format = '([\[$all_status$ahead_behind\]]($style))'

[nodejs]
symbol = ""
style = "bg:#98BB6C fg:#98BB6C"
format = '[[](fg:#98BB6C)[$symbol ($version)](fg:#0D0D0D bg:#98BB6C)]($style)[](fg:#98BB6C)'

[rust]
symbol = ""
style = "bg:#665C54"
format = '[[](fg:#D4A06F)[$symbol ($version)](fg:#0D0D0D bg:#D4A06F)]($style)[](fg:#D4A06F)'

[python]
symbol = ""
style = "bg:#7E9CD8"
format = '[[](fg:#7E9CD8)[$symbol ($version)](fg:#7FB4CA bg:#7E9CD8)]($style)[](fg:#7E9CD8)'

[kotlin]
symbol = "󱈙"
style = "bg:#7E9CD8"
format = '[[](fg:#7E9CD8)[$symbol ($version)](fg:#7FB4CA bg:#7E9CD8)]($style)[](fg:#7E9CD8)'

[terraform]
symbol = "󱁢"
style = "bg:#6837AA"
format = '[[](fg:#6837AA)[$symbol ($version)](fg:#DCD7BA bg:#6837AA)]($style)[](fg:#6837AA)'
