-- https://wiki.hypr.land/Configuring/Start/

--hl.config({ autogenerated = true }) -- remove this line to remove the warning

require("hyprland/autostart")
require("hyprland/behavior")
require("hyprland/cursor")
require("hyprland/env")
require("hyprland/input")
require("hyprland/single_window_pseudo") -- before apps so solo-unset runs before Steam Friends splitratio
require("hyprland/apps") -- app cmds, window rules, launch binds
require("hyprland/keybindings")
require("hyprland/monitor")
require("hyprland/permissions")
require("hyprland/style")
require("hyprland/workspaces")

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        disable_splash_rendering = true,
        force_default_wallpaper  = -1,
        disable_hyprland_logo    = true,
        background_color         = "0x000000",
    }
})
