-- https://wiki.hypr.land/Configuring/Start/

--hl.config({ autogenerated = true }) -- remove this line to remove the warning

require("autostart")
require("behavior")
require("cursor")
require("env")
require("input")
require("keybindings")
require("monitor")
require("permissions")
require("style")
require("1password")

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})

